Rust: Add methods to `Flavour` to get each colour
catppuccin/palette pull request #32
Opened 2022-10-26 21:48 UTC by nyxkrage

This adds method to get each of the colors directly from the `Flavour` variants like so
```rust
Flavour::Latte.teal()
```
rather than needing to go through the `FlavourColours` struct

This closes #27

2022-10-26 23:01 UTC, sgoudham requested changes

2022-10-26 23:01 UTC, sgoudham commented on rust/src/flavour.rs
> +        // Because if the correct method exists it is guaurenteed to access to correctly named field
```suggestion
        // Because if the correct method exists it is guaranteed to access to the correctly named field
```

2022-10-27 07:11 UTC, nyxkrage commented
Lmao, I forgot to turn on spellcheck

2022-10-27 15:29 UTC, sgoudham requested changes
Sorry I can't read

2022-10-27 15:29 UTC, sgoudham commented on rust/src/flavour.rs
> +        // Because if the correct method exists it is guaranteed to access to the correctly named field
```suggestion
        // Because if the correct method exists, it is guaranteed access to the correctly named field
```

2022-10-27 16:20 UTC, sgoudham approved these changes
LGTM!

2022-10-27 16:37 UTC, merged